minimum_pre_commit_version: 1.21.0
repos:
- repo: meta
  hooks:
  - id: check-hooks-apply
  - id: check-useless-excludes

# reorder Python imports
- repo: https://github.com/asottile/reorder_python_imports
  rev: v1.9.0
  hooks:
  - id: reorder-python-imports

# format Python code with black
- repo: https://github.com/ambv/black
  rev: 19.10b0
  hooks:
  - id: black

# # check docstrings
# - repo: https://github.com/PyCQA/pydocstyle
#   rev: 5.0.2
#   hooks:
#   - id: pydocstyle
#     args: ["--ignore=D10,D21,D202"]

# # static type checking with mypy
# - repo: https://github.com/pre-commit/mirrors-mypy
#   rev: v0.761
#   hooks:
#   - id: mypy

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.4.0
  hooks:
  - id: check-added-large-files
  - id: check-docstring-first
  - id: debug-statements
  - id: end-of-file-fixer
  # - id: flake8
    additional_dependencies: ["flake8-bugbear"]
  - id: trailing-whitespace
  - id: check-ast
  - id: check-builtin-literals
  - id: detect-private-key
  - id: mixed-line-ending
